# Generated by Django 4.1.3 on 2022-11-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind_of_problem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
