# Generated by Django 4.1.3 on 2022-11-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0002_kind_of_problem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind_of_problem',
            name='naming',
            field=models.CharField(max_length=50),
        ),
    ]
