# Generated by Django 4.1.3 on 2022-11-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0003_alter_kind_of_problem_naming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind_of_problem',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
