# Generated by Django 4.1.3 on 2022-11-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0004_alter_kind_of_problem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(max_length=50, verbose_name='Наименование возможной проблемы')),
                ('description', models.CharField(max_length=255, verbose_name='Описание возможной проблемы')),
            ],
            options={
                'verbose_name': 'Возможная проблема',
                'verbose_name_plural': 'Возможные проблемы',
            },
        ),
        migrations.DeleteModel(
            name='Kind_of_Problem',
        ),
    ]
