# Generated by Django 4.1.3 on 2022-11-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0005_problem_delete_kind_of_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
