# Generated by Django 4.1.3 on 2022-11-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0006_problem_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Изображение'),
        ),
    ]
