# Generated by Django 4.1.3 on 2022-11-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0009_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='section',
        ),
        migrations.AddField(
            model_name='faq',
            name='problem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psu.problem'),
        ),
    ]
