# Generated by Django 4.1.3 on 2022-11-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0010_remove_faq_section_faq_problem_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['problem_id'], 'verbose_name': 'Часто задаваемый вопрос', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='problem_id',
        ),
        migrations.AddField(
            model_name='faq',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psu.problem', verbose_name='Индентификатотр проблемы'),
        ),
    ]
