# Generated by Django 4.1.3 on 2022-12-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0011_alter_faq_options_remove_faq_problem_id_faq_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='extension_field',
            field=models.JSONField(blank=True, default={}, verbose_name='Дополнительные поля'),
        ),
    ]
