# Generated by Django 4.1.3 on 2022-12-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0012_problem_extension_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='extension_field',
        ),
        migrations.CreateModel(
            name='typeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaking', models.CharField(blank=True, max_length=255, verbose_name='Наименование возможной проблемы')),
                ('extension', models.JSONField(blank=True, default={}, verbose_name='Дополнительные поля')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psu.problem', verbose_name='Индентификатотр проблемы')),
            ],
        ),
    ]
