# Generated by Django 4.1.3 on 2022-12-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0013_remove_problem_extension_field_typeproblem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeproblem',
            options={'verbose_name': 'Вариант проблемы', 'verbose_name_plural': 'Варианты проблем'},
        ),
    ]
