# Generated by Django 4.1.3 on 2022-12-07 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0011_alter_faq_options_remove_faq_problem_id_faq_problem'),
        ('users', '0002_alter_customuser_options_customuser_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='должность')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU', verbose_name='Номер телефона')),
                ('kind_of_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='psu.problem', verbose_name='Вид проблемы')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Индентификатотр пользователя')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['user_id'],
            },
        ),
    ]
