# Generated by Django 4.1.3 on 2022-12-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='additional_info',
            field=models.JSONField(blank=True, default={}, verbose_name='Дополнительная информация'),
        ),
    ]
