# Generated by Django 4.1.3 on 2022-12-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_applications_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('SU', 'успешно завершена'), ('NW', 'новая заявка'), ('RE', 'заявка отклонена'), ('AI', 'требуется уточнение'), ('IP', 'в процессе выполнения'), ('CH', 'проверка')], default='NW', max_length=2, verbose_name='Статус'),
        ),
    ]
