# Generated by Django 4.1.3 on 2022-12-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0013_remove_problem_extension_field_typeproblem'),
        ('users', '0005_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='kind_of_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='psu.typeproblem', verbose_name='Вид проблемы'),
        ),
    ]
