# Generated by Django 4.1.3 on 2022-12-08 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0014_alter_typeproblem_options'),
        ('users', '0006_alter_applications_kind_of_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='psu.problem', verbose_name='Вид пробдлемы'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='kind_of_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='psu.typeproblem', verbose_name='Вариант проблемы'),
        ),
    ]
