# Generated by Django 4.1.3 on 2022-12-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_applications_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='name',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='surname',
        ),
        migrations.AddField(
            model_name='applications',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО'),
        ),
    ]
