# Generated by Django 4.1.3 on 2022-12-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_applications_name_remove_applications_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
    ]
