# Generated by Django 4.1.3 on 2022-12-10 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_applications_tel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='applications',
            name='user',
        ),
    ]
