# Generated by Django 4.1.3 on 2022-12-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_applications_options_remove_applications_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='status',
        ),
        migrations.AlterField(
            model_name='applications',
            name='kind_of_problem',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование проблемы'),
        ),
    ]
